# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  wormhole:
    target: ':wormhole'
    import: 'package:wormhole_generator/builder.dart'
    builder_factories: ['flutterWormHoleBuilder']
    build_extensions: { '.dart': ['.wormhole.g.part'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
