name: flutter_bridge_generator
description: Flutter Platform Bridge generator a classes depending on annotations to communicate with current platform (inspired by Retrofit)
version: 1.0.0

authors:
  - Florent Champigny <champigny.florent@gmail.com>

homepage: https://github.com/florent37/FlutterBridge

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^0.9.4+2
  built_collection: ^4.2.0
  code_builder: ^3.2.0
  flutter_bridge:
dev_dependencies:
  test:
  source_gen_test: any
  mock_web_server: ^4.1.1
  resource:
  flutter_test:
    sdk: flutter


dependency_overrides:
  flutter_bridge:
    path: ../flutter_bridge