name: flutter_bridge
description: Flutter Platform Bridge generator a classes depending on annotations to communicate with current platform (inspired by Retrofit)
version: 0.0.1
author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/florent37/FlutterBridge

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.github.florent37.flutterbridge
    pluginClass: FlutterBridgePlugin